- name: Add an apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: D68FA50FEA312927
  tags: install
- name: Add MongoDB repo
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
    update_cache: yes
  tags: install
- name: Install MongoDB
  apt:
    name: mongodb-org
  tags: install
- name: Enable MongoDB
  systemd:
    name: mongod
    enabled: yes
  tags: install
